Login:
    SecurityFirewall: Admin
    2FactorAuth: true # is 2 factor auth on or off
    BlockThreshold: 6 # after how many attempts should be block the login for that (ip+username) combination
    BlockTimelimit: 10 # when user hits the block treshold, how many minutes for should he be blocked
    SessionTtl: 30 # session TTL in days
    DeviceTtl: 90
    RateLimit: 10 # number of login attempts within 60 seconds from a single IP
    RateLimitBlacklist:
        - 123.123.123.123
    RateLimitWhitelist:
        - 127.0.0.1
        - 192.168.1.1
        - 10.0.2.2